name: discord-banners-server

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    network_mode: host
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always