name: discord-banners-server

services:
  server:
    image: discord-banners-server-image
    network_mode: host
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always