name: discord-banners-server

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis
    restart: always


  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always

volumes:
  redis-data:
    driver: local